//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaslandsTeamBuilderDataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perk()
        {
            this.Builds = new HashSet<Build>();
        }
    
        public int Key { get; set; }
        public string Name { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<int> CanCost { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sponsor { get; set; }
    
        public virtual PerkClass PerkClass { get; set; }
        public virtual Sponsor Sponsor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Build> Builds { get; set; }
    }
}
