//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaslandsTeamBuilderDataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upgrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Upgrade()
        {
            this.BuildUpgrades = new HashSet<BuildUpgrade>();
        }
    
        public int Key { get; set; }
        public string Name { get; set; }
        public Nullable<int> CanCost { get; set; }
        public Nullable<int> BuildSlotCost { get; set; }
        public Nullable<int> HullEffect { get; set; }
        public Nullable<int> HandlingEffect { get; set; }
        public Nullable<int> MaxGearEffect { get; set; }
        public Nullable<int> CrewEffect { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuildUpgrade> BuildUpgrades { get; set; }
    }
}
