//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaslandsTeamBuilderDataRepo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Builds = new HashSet<Build>();
        }
    
        public int Key { get; set; }
        public string Name { get; set; }
        public string WeightClass { get; set; }
        public Nullable<int> Hull { get; set; }
        public Nullable<int> Handling { get; set; }
        public Nullable<int> MaxGear { get; set; }
        public Nullable<int> Crew { get; set; }
        public Nullable<int> BuildSlots { get; set; }
        public Nullable<int> CanCost { get; set; }
        public string SpecialRules { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Build> Builds { get; set; }
    }
}
